### ISSUE TITLE
.repo is bad? and  default.xml is not available?

### ISSUE THREAD

**Issue by MenuuTUX** [RedWolfRecovery/rw_manifest#6]
So I tried to to follow the steps listed, but I got this error:

fatal: manifest 'default.xml' not available
fatal: <project> invalid "path": TeamWin/.repo/frameworks/base: bad component: .repo

What's the fix?

**Comment by WolfLink115** [comment]
I think you can just remove the "TeamWin/.repo/ part from the .repo/manifests/rw.xml and it should init properly. I also noticed there is an extra "/>" floating around after the bottom most "</project>" line, removing that might also be necessary.

Also, I know I am about 1 and a half years late to this so I assume you might have already figured it out.

**Comment by MenuuTUX** [comment]
This would of been helpful about a year ago but thanks lol. It looks like such a dumb mistake too.

**Comment by WolfLink115** [comment]
Yeah my bad. I didn't ever see this since I usually the rw-n branch, but used the rw branch and got that issue and wondered if anyone else ever had that happen.

I never got the build to work (since the device I am working with happens to be a vr headset and RWRP is kinda weird with it.)
I managed to get the ramdisk imbedded into the original boot image and got it to work, but it looked terrible lol.

Either way if you try this again, good luck!

**Comment by MenuuTUX** [comment]
Thanks for the help!
